#!/bin/bash

url=$1
token=$2

# pick your encoder
encoder="h264_nvenc"

# streamlink options
streamLink="streamlink --hls-segment-ignore-names preloading --hls-timeout 600  --http-cookie=authorization=$token $url best --ffmpeg-video-transcode copy --stdout"

$streamLink | /opt/ffmpeg/bin/ffmpeg -y -hide_banner -i pipe:0 \
	-preset slow -g 120 -sc_threshold 0 \
	-map 0:0 -map 0:1 -map 0:0 -map 0:1 -map 0:0 -map 0:1 \
	-s:v:0 320x180 -c:v:0 $encoder -maxrate 250k -rc cbr -b:v:0 250k \
	-s:v:1 640x360 -c:v:1 $encoder -maxrate 1420k -rc cbr -b:v:1 1420k \
	-s:v:2 copy -c:v:2 copy -c:a copy \
	-var_stream_map "v:0,a:0 v:1,a:1 v:2,a:2 " \
	-master_pl_name master.m3u8 \
	-f hls -hls_time 6 -hls_list_size 0 \
      	-hls_segment_filename "stream%v/fileSequence%d.ts" \
        "stream%v/playlist.m3u8"
